# Generated by Django 3.2.1 on 2021-05-04 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2021, 5, 4)),
            preserve_default=False,
        ),
    ]
