# Generated by Django 3.2.1 on 2021-05-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0003_activity_activity_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_end',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
