# Generated by Django 3.2.1 on 2021-05-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0004_auto_20210505_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_date',
        ),
    ]
