# Generated by Django 3.2.1 on 2021-05-05 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0005_remove_activity_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_duration',
            field=models.DurationField(default=datetime.timedelta()),
            preserve_default=False,
        ),
    ]
