# Generated by Django 3.2.1 on 2021-05-05 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0007_alter_activity_activity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
